# Generated by Django 6.0.1 on 2026-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_courses_profile_is_complete_profile_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
