# Generated by Django 6.0.1 on 2026-04-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], default='jobseeker', max_length=20),
        ),
    ]
