# Generated by Django 6.0.1 on 2026-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_admin_selected',
            field=models.BooleanField(default=False),
        ),
    ]
